---
- name: Home work 4
  hosts: carrier
  tasks:
    - name: Display Configuration Variables
      ansible.builtin.debug:
        msg:
          - "wordpress: {{ is_wordpress }}" # True or False
          - "wordpress_port: {{ wordpress_port }}" # 80 or 8080 or whatewer
          - "wordpress_db_name: {{ wordpress_db_name }}" # WP database name
          - "db1_host: {{ db1_host }}" # container name
          - "db2_host: {{ db2_host }}" # container name
          - "db3_host: {{ db3_host }}" # container name
          - "db4_host: {{ db4_host }}" # container name
          - "db5_host: {{ db5_host }}" # container name
          - "db_pass: {{ db_pass }}" # root password for DBs
          - "loadbalancer: {{ loadbalancer }}" # container name
          - "monitoring_url: {{ monitoring_url }}" # monitoring url including port
